name: Daily Commit Workflow

on:
  schedule:
    # Runs every day at 07:30 UTC (you can adjust the time)
    - cron: '30 7 * * *'
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add daily commit (22f3003001@ds.study.iitm.ac.in)
        run: |
          echo "Daily update on $(date)" >> daily_log.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily_log.txt
          git commit -m "Automated daily commit on $(date)"
          git push
